# Exported from Insomnia REST
POST /findInSeries HTTP/1.1
Content-Type: application/json
User-Agent: insomnia/11.3.0
Host: localhost:8080
Content-Length: 106

{
  "series_start": 0,
  "series_end": 11,
  "series_increment": 4,
  "series_type": 1,
  "specified_digit":1
}